language: node_js

node_js:
    - stable

cache: yarn

before_install:
    # Required due to: https://github.com/travis-ci/travis-ci/issues/7951
    - curl -sSfL https://yarnpkg.com/install.sh | bash
    - export PATH=$HOME/.yarn/bin:$PATH

install: yarn --frozen-lockfile

script: yarn run lint-quiet
